#!/bin/sh
#
# etherpad-lite - this script starts and stops the etherpad light daemon
#
# chkconfig: - 64 36
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 2 3 4 6
# Required-Start:
# description: etherpad lite is a collaboration editor
# processname: node

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

progname="Etherpad Lite"
path="/opt/etherpad/etherpad-lite"
prog="/usr/bin/node"
parameter="node_modules/ep_etherpad-lite/node/server.js"
log="$path/log/error.log"
conf="$path/settings.json"
user="etherpad"
logpath=$(dirname $log)

start() {
        [ -x $prog ] || exit 5
        [ -f $conf ] || exit 6
        [ -d $logpath ] || mkdir $logpath
        [ -f $log ] || touch $log
        chown $user.$user $logpath
        chown $user.$user $log

        cat <<'EOF' >$path/start.sh
#!/bin/bash
cd $(dirname $0)
/usr/bin/node $1 >>$2 &
EOF
        chown $user.$user $path/start.sh
        chmod u+x $path/start.sh
        echo -n $"Starting : "
        daemon --user=$user $path/start.sh $parameter $log
        retval=$?
        echo
        return $retval
}

stop() {
        echo -n $"Stopping $progname: "
        pkill -f $prog
        retval=$?
        echo "Done."
        return $retval
}

restart() {
        stop
        start
}

rh_status() {
        echo "Running procs:"
        pgrep -f $prog
}

rh_status_q() {
        rh_status >/dev/null 2>&1
}

case "$1" in
        start)
                rh_status_q && exit 0
                $1
        ;;
        stop)
                rh_status_q || exit 0
                $1
        ;;
        restart)
                $1
        ;;
        status)
                rh_status
        ;;
        *)
                echo $"Usage: $0 {start|stop|status|restart}"
                exit 2
esac
